pip 10.0.1 parse_requirements
If using pip >= 10.0.1 the "req" module has been moved.  Added changes check the user pip version and imports parse_requirements.

This came about because I continued to get the error: 

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dos34K/pyhrf/setup.py", line 117, in <module>
        setup_package()
      File "/tmp/pip-install-dos34K/pyhrf/setup.py", line 47, in setup_package
        dependencies = list(pip.req.parse_requirements('requirements.txt'))
AttributeError: 'module' object has no attribute 'req'

I was using pip version 10.0.1, and once I reverted to version 9.0.3 the error was resolved